branch-defaults:
  default:
    environment: Web5-env
  main:
    environment: Web5-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Web2-env:
    branch: null
    repository: null
  Web5-env:
    branch: null
    repository: null
global:
  application_name: web5
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
